#!/bin/bash

# Deploy script for installed the contents of this repo
LOG=~/deploy_deploy-test.log
DATE="`date --iso-8601='seconds'`"
echo "$DATE: `which python`" > $LOG
output=`pip install .`
echo "$DATE: $output" >> $LOG
